--- drivers/staging/zram/Makefile
+++ drivers/staging/zram/Makefile
@@ -1,4 +1,5 @@
 zram-y	:=	zram_drv.o zram_sysfs.o
-
+obj-y += lz4_compress.o
+obj-y += lz4_decompress.o
 obj-$(CONFIG_ZRAM)	+=	zram.o
-obj-$(CONFIG_XVMALLOC)	+=	xvmalloc.o+obj-$(CONFIG_XVMALLOC)	+=	xvmalloc.o
